


"""
Python Wrapper for the samplerz_axi register model

This code was generated from the PeakRDL-python package version 1.1.0

"""

from typing import Union

from ..sim_lib.register import Register, MemoryRegister
from ..sim_lib.memory import Memory
from ..sim_lib.simulator import MemoryEntry
from ..sim_lib.field import FieldDefinition

from ..sim_lib.simulator import Simulator

class samplerz_axi_simulator_cls(Simulator):

    def _build_registers(self) -> dict[int, Union[MemoryRegister, Register]]:
        return {
            0 : Register(width=32, full_inst_name='samplerz_axi.marker', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            4 : Register(width=32, full_inst_name='samplerz_axi.control', readable=True, writable=True,
                                         fields=[FieldDefinition(high=0, low=0, msb=0, lsb=0, inst_name='falcon1024'),FieldDefinition(high=1, low=1, msb=1, lsb=1, inst_name='done'),FieldDefinition(high=2, low=2, msb=2, lsb=2, inst_name='start'),FieldDefinition(high=3, low=3, msb=3, lsb=3, inst_name='stop'),FieldDefinition(high=4, low=4, msb=4, lsb=4, inst_name='continuous'),FieldDefinition(high=5, low=5, msb=5, lsb=5, inst_name='reset'),FieldDefinition(high=6, low=6, msb=6, lsb=6, inst_name='busy'),FieldDefinition(high=7, low=7, msb=7, lsb=7, inst_name='rand_full'),
                                                ]),
            8 : Register(width=64, full_inst_name='samplerz_axi.busy_cycles', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            16 : Register(width=64, full_inst_name='samplerz_axi.consumed_bits', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            24 : Register(width=64, full_inst_name='samplerz_axi.sginv', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            32 : Register(width=64, full_inst_name='samplerz_axi.mu1', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            40 : Register(width=64, full_inst_name='samplerz_axi.mu2', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            48 : Register(width=32, full_inst_name='samplerz_axi.z1', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            52 : Register(width=32, full_inst_name='samplerz_axi.z2', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            64 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[0]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            68 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[1]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            72 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[2]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            76 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[3]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            80 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[4]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            84 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[5]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            88 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[6]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            92 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[7]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            96 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[8]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            100 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[9]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            104 : Register(width=32, full_inst_name='samplerz_axi.prng.seed[10]', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            112 : Register(width=64, full_inst_name='samplerz_axi.prng.counter', readable=True, writable=True,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            512 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[0]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            520 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[1]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            528 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[2]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            536 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[3]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            544 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[4]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            552 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[5]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            560 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[6]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            568 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[7]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            576 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[8]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            584 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[9]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            592 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[10]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            600 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[11]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            608 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[12]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            616 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[13]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            624 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[14]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            632 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[15]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            640 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[16]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            648 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[17]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            656 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[18]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            664 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[19]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            672 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[20]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            680 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[21]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            688 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[22]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            696 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[23]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            704 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[24]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            712 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[25]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            720 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[26]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            728 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[27]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            736 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[28]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            744 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[29]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            752 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[30]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            760 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[31]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            768 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[32]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            776 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[33]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            784 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[34]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            792 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[35]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            800 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[36]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            808 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[37]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            816 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[38]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            824 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[0].histogram[39]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            832 : Register(width=32, full_inst_name='samplerz_axi.sample_histograms[0].pivot_value', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            836 : Register(width=32, full_inst_name='samplerz_axi.sample_histograms[0].pivot_index', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            840 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[0]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            848 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[1]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            856 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[2]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            864 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[3]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            872 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[4]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            880 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[5]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            888 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[6]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            896 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[7]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            904 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[8]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            912 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[9]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            920 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[10]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            928 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[11]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            936 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[12]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            944 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[13]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            952 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[14]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            960 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[15]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            968 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[16]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            976 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[17]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            984 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[18]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            992 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[19]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1000 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[20]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1008 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[21]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1016 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[22]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1024 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[23]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1032 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[24]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1040 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[25]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1048 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[26]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1056 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[27]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1064 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[28]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1072 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[29]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1080 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[30]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1088 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[31]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1096 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[32]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1104 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[33]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1112 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[34]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1120 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[35]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1128 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[36]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1136 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[37]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1144 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[38]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1152 : Register(width=64, full_inst_name='samplerz_axi.sample_histograms[1].histogram[39]', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='low'),FieldDefinition(high=63, low=32, msb=63, lsb=32, inst_name='high'),
                                                ]),
            1160 : Register(width=32, full_inst_name='samplerz_axi.sample_histograms[1].pivot_value', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
            1164 : Register(width=32, full_inst_name='samplerz_axi.sample_histograms[1].pivot_index', readable=True, writable=False,
                                         fields=[FieldDefinition(high=31, low=0, msb=31, lsb=0, inst_name='data'),
                                                ]),
        }

    def _build_memories(self) -> list[MemoryEntry]:
        return [
        ]

if __name__ == '__main__':
    pass
