_list:
    @just -l

env:
    python3.14 -m venv --clear .venv
    .venv/bin/python -m pip install -r requirements.txt

decompress:
    tar -xJf samples.tar.xz --overwrite

# Run the analysis notebook. Note that it is distributed pre-run including the output plots.
analyze:
    .venv/bin/python -m nbconvert --to notebook --execute --inplace --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 notebook.ipynb

compress tg="samples.tar.xz":
    tar -cf - samples_sim samples_hw samples_hw_hist | pixz -9 > "{{tg}}"
