// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module samplerz_axi (
        input wire clk,
        input wire rst,

        axi4lite_intf.slave s_axil,

        input samplerz_axi_pkg::samplerz_axi__in_t hwif_in,
        output samplerz_axi_pkg::samplerz_axi__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [10:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert($bits(s_axil.ARADDR) >= samplerz_axi_pkg::SAMPLERZ_AXI_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_axil.ARADDR), samplerz_axi_pkg::SAMPLERZ_AXI_MIN_ADDR_WIDTH);
            assert($bits(s_axil.WDATA) == samplerz_axi_pkg::SAMPLERZ_AXI_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_axil.WDATA), samplerz_axi_pkg::SAMPLERZ_AXI_DATA_WIDTH);
        end
    `endif

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [10:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [10:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(rst) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil.ARVALID && s_axil.ARREADY) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil.ARADDR;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil.AWVALID && s_axil.AWREADY) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil.AWADDR;
            end
            if(s_axil.WVALID && s_axil.WREADY) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil.WDATA;
                axil_wstrb <= s_axil.WSTRB;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil.ARREADY = (!axil_arvalid || axil_ar_accept);
        s_axil.AWREADY = (!axil_awvalid || axil_aw_accept);
        s_axil.WREADY = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[10:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[10:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[10:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [31:0] rdata;
    } axil_resp_buffer[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(rst) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[0:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil.BVALID = '0;
        s_axil.RVALID = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[0:0]].is_wr) begin
                s_axil.BVALID = '1;
                if(s_axil.BREADY) axil_resp_acked = '1;
            end else begin
                s_axil.RVALID = '1;
                if(s_axil.RREADY) axil_resp_acked = '1;
            end
        end

        s_axil.RDATA = axil_resp_buffer[axil_resp_rptr[0:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[0:0]].err) begin
            s_axil.BRESP = 2'b10;
            s_axil.RRESP = 2'b10;
        end else begin
            s_axil.BRESP = 2'b00;
            s_axil.RRESP = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic marker;
        logic control;
        logic [1:0] busy_cycles;
        logic [1:0] consumed_bits;
        logic [1:0] sginv;
        logic [1:0] mu1;
        logic [1:0] mu2;
        logic z1;
        logic z2;
        struct {
            logic seed[11];
            logic [1:0] counter;
        } prng;
        struct {
            logic [1:0] histogram[40];
            logic pivot_value;
            logic pivot_index;
        } sample_histograms[2];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.marker = cpuif_req_masked & (cpuif_addr == 11'h0);
        decoded_reg_strb.control = cpuif_req_masked & (cpuif_addr == 11'h4);
        decoded_reg_strb.busy_cycles[0] = cpuif_req_masked & (cpuif_addr == 11'h8);
        decoded_reg_strb.busy_cycles[1] = cpuif_req_masked & (cpuif_addr == 11'hc);
        decoded_reg_strb.consumed_bits[0] = cpuif_req_masked & (cpuif_addr == 11'h10);
        decoded_reg_strb.consumed_bits[1] = cpuif_req_masked & (cpuif_addr == 11'h14);
        decoded_reg_strb.sginv[0] = cpuif_req_masked & (cpuif_addr == 11'h18);
        decoded_reg_strb.sginv[1] = cpuif_req_masked & (cpuif_addr == 11'h1c);
        decoded_reg_strb.mu1[0] = cpuif_req_masked & (cpuif_addr == 11'h20);
        decoded_reg_strb.mu1[1] = cpuif_req_masked & (cpuif_addr == 11'h24);
        decoded_reg_strb.mu2[0] = cpuif_req_masked & (cpuif_addr == 11'h28);
        decoded_reg_strb.mu2[1] = cpuif_req_masked & (cpuif_addr == 11'h2c);
        decoded_reg_strb.z1 = cpuif_req_masked & (cpuif_addr == 11'h30);
        decoded_reg_strb.z2 = cpuif_req_masked & (cpuif_addr == 11'h34);
        for(int i0=0; i0<11; i0++) begin
            decoded_reg_strb.prng.seed[i0] = cpuif_req_masked & (cpuif_addr == 11'h40 + (11)'(i0) * 11'h4);
        end
        decoded_reg_strb.prng.counter[0] = cpuif_req_masked & (cpuif_addr == 11'h70);
        decoded_reg_strb.prng.counter[1] = cpuif_req_masked & (cpuif_addr == 11'h74);
        for(int i0=0; i0<2; i0++) begin
            for(int i1=0; i1<40; i1++) begin
                decoded_reg_strb.sample_histograms[i0].histogram[i1][0] = cpuif_req_masked & (cpuif_addr == 11'h200 + (11)'(i0) * 11'h148 + (11)'(i1) * 11'h8);
                decoded_reg_strb.sample_histograms[i0].histogram[i1][1] = cpuif_req_masked & (cpuif_addr == 11'h204 + (11)'(i0) * 11'h148 + (11)'(i1) * 11'h8);
            end
            decoded_reg_strb.sample_histograms[i0].pivot_value = cpuif_req_masked & (cpuif_addr == 11'h340 + (11)'(i0) * 11'h148);
            decoded_reg_strb.sample_histograms[i0].pivot_index = cpuif_req_masked & (cpuif_addr == 11'h344 + (11)'(i0) * 11'h148);
        end
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } falcon1024;
            struct {
                logic next;
                logic load_next;
            } start;
            struct {
                logic next;
                logic load_next;
            } stop;
            struct {
                logic next;
                logic load_next;
            } continuous;
            struct {
                logic next;
                logic load_next;
            } reset;
        } control;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } low;
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } high;
        } busy_cycles;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } low;
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } high;
        } consumed_bits;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } low;
            struct {
                logic [31:0] next;
                logic load_next;
            } high;
        } sginv;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } low;
            struct {
                logic [31:0] next;
                logic load_next;
            } high;
        } mu1;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } low;
            struct {
                logic [31:0] next;
                logic load_next;
            } high;
        } mu2;
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } data;
            } seed[11];
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                    logic incrthreshold;
                    logic overflow;
                } low;
                struct {
                    logic [31:0] next;
                    logic load_next;
                    logic incrthreshold;
                    logic overflow;
                } high;
            } counter;
        } prng;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } falcon1024;
            struct {
                logic value;
            } start;
            struct {
                logic value;
            } stop;
            struct {
                logic value;
            } continuous;
            struct {
                logic value;
            } reset;
        } control;
        struct {
            struct {
                logic [31:0] value;
            } low;
            struct {
                logic [31:0] value;
            } high;
        } busy_cycles;
        struct {
            struct {
                logic [31:0] value;
            } low;
            struct {
                logic [31:0] value;
            } high;
        } consumed_bits;
        struct {
            struct {
                logic [31:0] value;
            } low;
            struct {
                logic [31:0] value;
            } high;
        } sginv;
        struct {
            struct {
                logic [31:0] value;
            } low;
            struct {
                logic [31:0] value;
            } high;
        } mu1;
        struct {
            struct {
                logic [31:0] value;
            } low;
            struct {
                logic [31:0] value;
            } high;
        } mu2;
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } data;
            } seed[11];
            struct {
                struct {
                    logic [31:0] value;
                } low;
                struct {
                    logic [31:0] value;
                } high;
            } counter;
        } prng;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: samplerz_axi.control.falcon1024
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.falcon1024.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.falcon1024.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.control.falcon1024.next = next_c;
        field_combo.control.falcon1024.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.falcon1024.value <= 1'h0;
        end else begin
            if(field_combo.control.falcon1024.load_next) begin
                field_storage.control.falcon1024.value <= field_combo.control.falcon1024.next;
            end
        end
    end
    assign hwif_out.control.falcon1024.value = field_storage.control.falcon1024.value;
    // Field: samplerz_axi.control.start
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.start.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.start.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.control.start.next = next_c;
        field_combo.control.start.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.start.value <= 1'h0;
        end else begin
            if(field_combo.control.start.load_next) begin
                field_storage.control.start.value <= field_combo.control.start.next;
            end
        end
    end
    assign hwif_out.control.start.value = field_storage.control.start.value;
    // Field: samplerz_axi.control.stop
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.stop.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.stop.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.control.stop.next = next_c;
        field_combo.control.stop.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.stop.value <= 1'h0;
        end else begin
            if(field_combo.control.stop.load_next) begin
                field_storage.control.stop.value <= field_combo.control.stop.next;
            end
        end
    end
    assign hwif_out.control.stop.value = field_storage.control.stop.value;
    // Field: samplerz_axi.control.continuous
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.continuous.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.continuous.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.control.continuous.next = next_c;
        field_combo.control.continuous.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.continuous.value <= 1'h0;
        end else begin
            if(field_combo.control.continuous.load_next) begin
                field_storage.control.continuous.value <= field_combo.control.continuous.next;
            end
        end
    end
    assign hwif_out.control.continuous.value = field_storage.control.continuous.value;
    // Field: samplerz_axi.control.reset
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control.reset.value;
        load_next_c = '0;
        if(decoded_reg_strb.control && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control.reset.value & ~decoded_wr_biten[5:5]) | (decoded_wr_data[5:5] & decoded_wr_biten[5:5]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.control.reset.next = next_c;
        field_combo.control.reset.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control.reset.value <= 1'h0;
        end else begin
            if(field_combo.control.reset.load_next) begin
                field_storage.control.reset.value <= field_combo.control.reset.next;
            end
        end
    end
    assign hwif_out.control.reset.value = field_storage.control.reset.value;
    // Field: samplerz_axi.busy_cycles.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.busy_cycles.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.busy_cycles[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.busy_cycles.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.busy_cycles.low.incr) begin // increment
            field_combo.busy_cycles.low.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.busy_cycles.low.overflow = '0;
        end
        field_combo.busy_cycles.low.incrthreshold = (field_storage.busy_cycles.low.value >= 32'hffffffff);
        field_combo.busy_cycles.low.next = next_c;
        field_combo.busy_cycles.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(hwif_in.busy_cycles.reset_busy_cycles) begin
            field_storage.busy_cycles.low.value <= 32'h0;
        end else begin
            if(field_combo.busy_cycles.low.load_next) begin
                field_storage.busy_cycles.low.value <= field_combo.busy_cycles.low.next;
            end
        end
    end
    // Field: samplerz_axi.busy_cycles.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.busy_cycles.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.busy_cycles[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.busy_cycles.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(field_combo.busy_cycles.low.overflow) begin // increment
            field_combo.busy_cycles.high.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.busy_cycles.high.overflow = '0;
        end
        field_combo.busy_cycles.high.incrthreshold = (field_storage.busy_cycles.high.value >= 32'hffffffff);
        field_combo.busy_cycles.high.next = next_c;
        field_combo.busy_cycles.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(hwif_in.busy_cycles.reset_busy_cycles) begin
            field_storage.busy_cycles.high.value <= 32'h0;
        end else begin
            if(field_combo.busy_cycles.high.load_next) begin
                field_storage.busy_cycles.high.value <= field_combo.busy_cycles.high.next;
            end
        end
    end
    // Field: samplerz_axi.consumed_bits.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.consumed_bits.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.consumed_bits[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.consumed_bits.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.consumed_bits.low.incr) begin // increment
            field_combo.consumed_bits.low.overflow = (((33)'(next_c) + hwif_in.consumed_bits.low.incrvalue) > 32'hffffffff);
            next_c = next_c + hwif_in.consumed_bits.low.incrvalue;
            load_next_c = '1;
        end else begin
            field_combo.consumed_bits.low.overflow = '0;
        end
        field_combo.consumed_bits.low.incrthreshold = (field_storage.consumed_bits.low.value >= 32'hffffffff);
        field_combo.consumed_bits.low.next = next_c;
        field_combo.consumed_bits.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(hwif_in.consumed_bits.reset_consumed_bits) begin
            field_storage.consumed_bits.low.value <= 32'h0;
        end else begin
            if(field_combo.consumed_bits.low.load_next) begin
                field_storage.consumed_bits.low.value <= field_combo.consumed_bits.low.next;
            end
        end
    end
    // Field: samplerz_axi.consumed_bits.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.consumed_bits.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.consumed_bits[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.consumed_bits.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(field_combo.consumed_bits.low.overflow) begin // increment
            field_combo.consumed_bits.high.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.consumed_bits.high.overflow = '0;
        end
        field_combo.consumed_bits.high.incrthreshold = (field_storage.consumed_bits.high.value >= 32'hffffffff);
        field_combo.consumed_bits.high.next = next_c;
        field_combo.consumed_bits.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(hwif_in.consumed_bits.reset_consumed_bits) begin
            field_storage.consumed_bits.high.value <= 32'h0;
        end else begin
            if(field_combo.consumed_bits.high.load_next) begin
                field_storage.consumed_bits.high.value <= field_combo.consumed_bits.high.next;
            end
        end
    end
    // Field: samplerz_axi.sginv.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sginv.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.sginv[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.sginv.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.sginv.low.next = next_c;
        field_combo.sginv.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.sginv.low.load_next) begin
            field_storage.sginv.low.value <= field_combo.sginv.low.next;
        end
    end
    assign hwif_out.sginv.low.value = field_storage.sginv.low.value;
    // Field: samplerz_axi.sginv.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sginv.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.sginv[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.sginv.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.sginv.high.next = next_c;
        field_combo.sginv.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.sginv.high.load_next) begin
            field_storage.sginv.high.value <= field_combo.sginv.high.next;
        end
    end
    assign hwif_out.sginv.high.value = field_storage.sginv.high.value;
    // Field: samplerz_axi.mu1.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mu1.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.mu1[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mu1.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.mu1.low.next = next_c;
        field_combo.mu1.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.mu1.low.load_next) begin
            field_storage.mu1.low.value <= field_combo.mu1.low.next;
        end
    end
    assign hwif_out.mu1.low.value = field_storage.mu1.low.value;
    // Field: samplerz_axi.mu1.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mu1.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.mu1[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mu1.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.mu1.high.next = next_c;
        field_combo.mu1.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.mu1.high.load_next) begin
            field_storage.mu1.high.value <= field_combo.mu1.high.next;
        end
    end
    assign hwif_out.mu1.high.value = field_storage.mu1.high.value;
    // Field: samplerz_axi.mu2.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mu2.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.mu2[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mu2.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.mu2.low.next = next_c;
        field_combo.mu2.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.mu2.low.load_next) begin
            field_storage.mu2.low.value <= field_combo.mu2.low.next;
        end
    end
    assign hwif_out.mu2.low.value = field_storage.mu2.low.value;
    // Field: samplerz_axi.mu2.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mu2.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.mu2[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.mu2.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.mu2.high.next = next_c;
        field_combo.mu2.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.mu2.high.load_next) begin
            field_storage.mu2.high.value <= field_combo.mu2.high.next;
        end
    end
    assign hwif_out.mu2.high.value = field_storage.mu2.high.value;
    for(genvar i0=0; i0<11; i0++) begin
        // Field: samplerz_axi.prng.seed[].data
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.prng.seed[i0].data.value;
            load_next_c = '0;
            if(decoded_reg_strb.prng.seed[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.prng.seed[i0].data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.prng.seed[i0].data.next = next_c;
            field_combo.prng.seed[i0].data.load_next = load_next_c;
        end
        always_ff @(posedge clk) begin
            if(field_combo.prng.seed[i0].data.load_next) begin
                field_storage.prng.seed[i0].data.value <= field_combo.prng.seed[i0].data.next;
            end
        end
        assign hwif_out.prng.seed[i0].data.value = field_storage.prng.seed[i0].data.value;
    end
    // Field: samplerz_axi.prng.counter.low
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.prng.counter.low.value;
        load_next_c = '0;
        if(decoded_reg_strb.prng.counter[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.prng.counter.low.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.prng.counter.low.incr) begin // increment
            field_combo.prng.counter.low.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.prng.counter.low.overflow = '0;
        end
        field_combo.prng.counter.low.incrthreshold = (field_storage.prng.counter.low.value >= 32'hffffffff);
        field_combo.prng.counter.low.next = next_c;
        field_combo.prng.counter.low.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.prng.counter.low.load_next) begin
            field_storage.prng.counter.low.value <= field_combo.prng.counter.low.next;
        end
    end
    assign hwif_out.prng.counter.low.value = field_storage.prng.counter.low.value;
    // Field: samplerz_axi.prng.counter.high
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.prng.counter.high.value;
        load_next_c = '0;
        if(decoded_reg_strb.prng.counter[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.prng.counter.high.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(field_combo.prng.counter.low.overflow) begin // increment
            field_combo.prng.counter.high.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.prng.counter.high.overflow = '0;
        end
        field_combo.prng.counter.high.incrthreshold = (field_storage.prng.counter.high.value >= 32'hffffffff);
        field_combo.prng.counter.high.next = next_c;
        field_combo.prng.counter.high.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.prng.counter.high.load_next) begin
            field_storage.prng.counter.high.value <= field_combo.prng.counter.high.next;
        end
    end
    assign hwif_out.prng.counter.high.value = field_storage.prng.counter.high.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[191];
    assign readback_array[0][31:0] = (decoded_reg_strb.marker && !decoded_req_is_wr) ? 32'h6663737a : '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.control && !decoded_req_is_wr) ? field_storage.control.falcon1024.value : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.control && !decoded_req_is_wr) ? hwif_in.control.done.next : '0;
    assign readback_array[1][2:2] = (decoded_reg_strb.control && !decoded_req_is_wr) ? field_storage.control.start.value : '0;
    assign readback_array[1][3:3] = (decoded_reg_strb.control && !decoded_req_is_wr) ? field_storage.control.stop.value : '0;
    assign readback_array[1][4:4] = (decoded_reg_strb.control && !decoded_req_is_wr) ? field_storage.control.continuous.value : '0;
    assign readback_array[1][5:5] = (decoded_reg_strb.control && !decoded_req_is_wr) ? field_storage.control.reset.value : '0;
    assign readback_array[1][6:6] = (decoded_reg_strb.control && !decoded_req_is_wr) ? hwif_in.control.busy.next : '0;
    assign readback_array[1][7:7] = (decoded_reg_strb.control && !decoded_req_is_wr) ? hwif_in.control.rand_full.next : '0;
    assign readback_array[1][31:8] = '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.busy_cycles[0] && !decoded_req_is_wr) ? field_storage.busy_cycles.low.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.busy_cycles[1] && !decoded_req_is_wr) ? field_storage.busy_cycles.high.value : '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.consumed_bits[0] && !decoded_req_is_wr) ? field_storage.consumed_bits.low.value : '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.consumed_bits[1] && !decoded_req_is_wr) ? field_storage.consumed_bits.high.value : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.sginv[0] && !decoded_req_is_wr) ? field_storage.sginv.low.value : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.sginv[1] && !decoded_req_is_wr) ? field_storage.sginv.high.value : '0;
    assign readback_array[8][31:0] = (decoded_reg_strb.mu1[0] && !decoded_req_is_wr) ? field_storage.mu1.low.value : '0;
    assign readback_array[9][31:0] = (decoded_reg_strb.mu1[1] && !decoded_req_is_wr) ? field_storage.mu1.high.value : '0;
    assign readback_array[10][31:0] = (decoded_reg_strb.mu2[0] && !decoded_req_is_wr) ? field_storage.mu2.low.value : '0;
    assign readback_array[11][31:0] = (decoded_reg_strb.mu2[1] && !decoded_req_is_wr) ? field_storage.mu2.high.value : '0;
    assign readback_array[12][31:0] = (decoded_reg_strb.z1 && !decoded_req_is_wr) ? hwif_in.z1.data.next : '0;
    assign readback_array[13][31:0] = (decoded_reg_strb.z2 && !decoded_req_is_wr) ? hwif_in.z2.data.next : '0;
    for(genvar i0=0; i0<11; i0++) begin
        assign readback_array[i0 * 1 + 14][31:0] = (decoded_reg_strb.prng.seed[i0] && !decoded_req_is_wr) ? field_storage.prng.seed[i0].data.value : '0;
    end
    assign readback_array[25][31:0] = (decoded_reg_strb.prng.counter[0] && !decoded_req_is_wr) ? field_storage.prng.counter.low.value : '0;
    assign readback_array[26][31:0] = (decoded_reg_strb.prng.counter[1] && !decoded_req_is_wr) ? field_storage.prng.counter.high.value : '0;
    for(genvar i0=0; i0<2; i0++) begin
        for(genvar i1=0; i1<40; i1++) begin
            assign readback_array[i0 * 82 + i1 * 2 + 27][31:0] = (decoded_reg_strb.sample_histograms[i0].histogram[i1][0] && !decoded_req_is_wr) ? hwif_in.sample_histograms[i0].histogram[i1].low.next : '0;
            assign readback_array[i0 * 82 + i1 * 2 + 28][31:0] = (decoded_reg_strb.sample_histograms[i0].histogram[i1][1] && !decoded_req_is_wr) ? hwif_in.sample_histograms[i0].histogram[i1].high.next : '0;
        end
        assign readback_array[i0 * 82 + 107][31:0] = (decoded_reg_strb.sample_histograms[i0].pivot_value && !decoded_req_is_wr) ? hwif_in.sample_histograms[i0].pivot_value.data.next : '0;
        assign readback_array[i0 * 82 + 108][31:0] = (decoded_reg_strb.sample_histograms[i0].pivot_index && !decoded_req_is_wr) ? hwif_in.sample_histograms[i0].pivot_index.data.next : '0;
    end

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<191; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
