// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package samplerz_axi_pkg;

    localparam SAMPLERZ_AXI_DATA_WIDTH = 32;
    localparam SAMPLERZ_AXI_MIN_ADDR_WIDTH = 11;
    localparam SAMPLERZ_AXI_SIZE = 'h490;

    

    typedef struct {
        logic next;
    } samplerz_axi__control__done__in_t;

    typedef struct {
        logic next;
    } samplerz_axi__control__busy__in_t;

    typedef struct {
        logic next;
    } samplerz_axi__control__rand_full__in_t;

    typedef struct {
        samplerz_axi__control__done__in_t done;
        samplerz_axi__control__busy__in_t busy;
        samplerz_axi__control__rand_full__in_t rand_full;
    } samplerz_axi__control__in_t;

    typedef struct {
        logic incr;
    } samplerz_axi__busy_cycles__low_resetsignal_9fa1e13e__in_t;

    typedef struct {
        logic reset_busy_cycles;
        samplerz_axi__busy_cycles__low_resetsignal_9fa1e13e__in_t low;
    } samplerz_axi__busy_cycles__in_t;

    typedef struct {
        logic incr;
        logic [31:0] incrvalue;
    } samplerz_axi__consumed_bits__low_resetsignal_22c88e8e__in_t;

    typedef struct {
        logic reset_consumed_bits;
        samplerz_axi__consumed_bits__low_resetsignal_22c88e8e__in_t low;
    } samplerz_axi__consumed_bits__in_t;

    typedef struct {
        logic [31:0] next;
    } samplerz_axi__hw2sw32__data__in_t;

    typedef struct {
        samplerz_axi__hw2sw32__data__in_t data;
    } samplerz_axi__hw2sw32__in_t;

    typedef struct {
        logic incr;
    } samplerz_axi__prng__counter__low__in_t;

    typedef struct {
        samplerz_axi__prng__counter__low__in_t low;
    } samplerz_axi__prng__counter__in_t;

    typedef struct {
        samplerz_axi__prng__counter__in_t counter;
    } samplerz_axi__prng__in_t;

    typedef struct {
        logic [31:0] next;
    } samplerz_axi__hw2sw64__low__in_t;

    typedef struct {
        logic [31:0] next;
    } samplerz_axi__hw2sw64__high__in_t;

    typedef struct {
        samplerz_axi__hw2sw64__low__in_t low;
        samplerz_axi__hw2sw64__high__in_t high;
    } samplerz_axi__hw2sw64__in_t;

    typedef struct {
        samplerz_axi__hw2sw64__in_t histogram[40];
        samplerz_axi__hw2sw32__in_t pivot_value;
        samplerz_axi__hw2sw32__in_t pivot_index;
    } samplerz_axi__sample_histogram__in_t;

    typedef struct {
        samplerz_axi__control__in_t control;
        samplerz_axi__busy_cycles__in_t busy_cycles;
        samplerz_axi__consumed_bits__in_t consumed_bits;
        samplerz_axi__hw2sw32__in_t z1;
        samplerz_axi__hw2sw32__in_t z2;
        samplerz_axi__prng__in_t prng;
        samplerz_axi__sample_histogram__in_t sample_histograms[2];
    } samplerz_axi__in_t;

    typedef struct {
        logic value;
    } samplerz_axi__control__falcon1024__out_t;

    typedef struct {
        logic value;
    } samplerz_axi__control__start__out_t;

    typedef struct {
        logic value;
    } samplerz_axi__control__stop__out_t;

    typedef struct {
        logic value;
    } samplerz_axi__control__continuous__out_t;

    typedef struct {
        logic value;
    } samplerz_axi__control__reset__out_t;

    typedef struct {
        samplerz_axi__control__falcon1024__out_t falcon1024;
        samplerz_axi__control__start__out_t start;
        samplerz_axi__control__stop__out_t stop;
        samplerz_axi__control__continuous__out_t continuous;
        samplerz_axi__control__reset__out_t reset;
    } samplerz_axi__control__out_t;

    typedef struct {
        logic [31:0] value;
    } samplerz_axi__sw2hw64__low__out_t;

    typedef struct {
        logic [31:0] value;
    } samplerz_axi__sw2hw64__high__out_t;

    typedef struct {
        samplerz_axi__sw2hw64__low__out_t low;
        samplerz_axi__sw2hw64__high__out_t high;
    } samplerz_axi__sw2hw64__out_t;

    typedef struct {
        logic [31:0] value;
    } samplerz_axi__sw2hw32__data__out_t;

    typedef struct {
        samplerz_axi__sw2hw32__data__out_t data;
    } samplerz_axi__sw2hw32__out_t;

    typedef struct {
        logic [31:0] value;
    } samplerz_axi__prng__counter__low__out_t;

    typedef struct {
        logic [31:0] value;
    } samplerz_axi__prng__counter__high_incr_8dad7f70__out_t;

    typedef struct {
        samplerz_axi__prng__counter__low__out_t low;
        samplerz_axi__prng__counter__high_incr_8dad7f70__out_t high;
    } samplerz_axi__prng__counter__out_t;

    typedef struct {
        samplerz_axi__sw2hw32__out_t seed[11];
        samplerz_axi__prng__counter__out_t counter;
    } samplerz_axi__prng__out_t;

    typedef struct {
        samplerz_axi__control__out_t control;
        samplerz_axi__sw2hw64__out_t sginv;
        samplerz_axi__sw2hw64__out_t mu1;
        samplerz_axi__sw2hw64__out_t mu2;
        samplerz_axi__prng__out_t prng;
    } samplerz_axi__out_t;
endpackage
