_list:
    @just -l

env:
    python3.14 -m venv --clear .venv
    .venv/bin/python -m pip install -r requirements.txt

peakrdl *ARGS:
    .venv/bin/peakrdl {{ARGS}}

RDL := "samplerz_axi.rdl regblock_udps.rdl"

dump:
    just peakrdl dump {{RDL}}
gen-sv:
    just peakrdl regblock {{RDL}} -o hw/ --cpuif axi4-lite
gen-sv-const:
    just peakrdl sv_const_exporter {{RDL}} -o hw/samplerz_axi_map_pkg.sv
gen-html:
    just peakrdl html {{RDL}} -o doc/
gen-c:
    mkdir -p sw/c
    just peakrdl c-header {{RDL}} -o sw/c/samplerz_axi.h
    just peakrdl c-header {{RDL}} -o sw/c/samplerz_axi_bitfield_little.h --bitfields ltoh
gen-py:
    just peakrdl python {{RDL}} -o sw/py/

gen: gen-sv gen-sv-const gen-html gen-c gen-py

all: env dump gen

clean:
    rm -rf sw hw
