// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef SAMPLERZ_AXI_BITFIELD_LITTLE_H
#define SAMPLERZ_AXI_BITFIELD_LITTLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - samplerz_axi::marker
#define SAMPLERZ_AXI__MARKER__DATA_bm 0xffffffff
#define SAMPLERZ_AXI__MARKER__DATA_bp 0
#define SAMPLERZ_AXI__MARKER__DATA_bw 32
#define SAMPLERZ_AXI__MARKER__DATA_reset 0x6663737a
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t data :32;
    } f;
    uint32_t w;
} samplerz_axi__marker_t;

// Reg - samplerz_axi::control
#define SAMPLERZ_AXI__CONTROL__FALCON1024_bm 0x1
#define SAMPLERZ_AXI__CONTROL__FALCON1024_bp 0
#define SAMPLERZ_AXI__CONTROL__FALCON1024_bw 1
#define SAMPLERZ_AXI__CONTROL__FALCON1024_reset 0x0
#define SAMPLERZ_AXI__CONTROL__DONE_bm 0x2
#define SAMPLERZ_AXI__CONTROL__DONE_bp 1
#define SAMPLERZ_AXI__CONTROL__DONE_bw 1
#define SAMPLERZ_AXI__CONTROL__DONE_reset 0x0
#define SAMPLERZ_AXI__CONTROL__START_bm 0x4
#define SAMPLERZ_AXI__CONTROL__START_bp 2
#define SAMPLERZ_AXI__CONTROL__START_bw 1
#define SAMPLERZ_AXI__CONTROL__START_reset 0x0
#define SAMPLERZ_AXI__CONTROL__STOP_bm 0x8
#define SAMPLERZ_AXI__CONTROL__STOP_bp 3
#define SAMPLERZ_AXI__CONTROL__STOP_bw 1
#define SAMPLERZ_AXI__CONTROL__STOP_reset 0x0
#define SAMPLERZ_AXI__CONTROL__CONTINUOUS_bm 0x10
#define SAMPLERZ_AXI__CONTROL__CONTINUOUS_bp 4
#define SAMPLERZ_AXI__CONTROL__CONTINUOUS_bw 1
#define SAMPLERZ_AXI__CONTROL__CONTINUOUS_reset 0x0
#define SAMPLERZ_AXI__CONTROL__RESET_bm 0x20
#define SAMPLERZ_AXI__CONTROL__RESET_bp 5
#define SAMPLERZ_AXI__CONTROL__RESET_bw 1
#define SAMPLERZ_AXI__CONTROL__RESET_reset 0x0
#define SAMPLERZ_AXI__CONTROL__BUSY_bm 0x40
#define SAMPLERZ_AXI__CONTROL__BUSY_bp 6
#define SAMPLERZ_AXI__CONTROL__BUSY_bw 1
#define SAMPLERZ_AXI__CONTROL__BUSY_reset 0x0
#define SAMPLERZ_AXI__CONTROL__RAND_FULL_bm 0x80
#define SAMPLERZ_AXI__CONTROL__RAND_FULL_bp 7
#define SAMPLERZ_AXI__CONTROL__RAND_FULL_bw 1
#define SAMPLERZ_AXI__CONTROL__RAND_FULL_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t falcon1024 :1;
        uint32_t done :1;
        uint32_t start :1;
        uint32_t stop :1;
        uint32_t continuous :1;
        uint32_t reset :1;
        uint32_t busy :1;
        uint32_t rand_full :1;
        uint32_t :24;
    } f;
    uint32_t w;
} samplerz_axi__control_t;

// Reg - samplerz_axi::busy_cycles
#define SAMPLERZ_AXI__BUSY_CYCLES__LOW_bm 0xffffffff
#define SAMPLERZ_AXI__BUSY_CYCLES__LOW_bp 0
#define SAMPLERZ_AXI__BUSY_CYCLES__LOW_bw 32
#define SAMPLERZ_AXI__BUSY_CYCLES__LOW_reset 0x0
#define SAMPLERZ_AXI__BUSY_CYCLES__HIGH_bm 0xffffffff00000000
#define SAMPLERZ_AXI__BUSY_CYCLES__HIGH_bp 32
#define SAMPLERZ_AXI__BUSY_CYCLES__HIGH_bw 32
#define SAMPLERZ_AXI__BUSY_CYCLES__HIGH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} samplerz_axi__busy_cycles_t;

// Reg - samplerz_axi::consumed_bits
#define SAMPLERZ_AXI__CONSUMED_BITS__LOW_bm 0xffffffff
#define SAMPLERZ_AXI__CONSUMED_BITS__LOW_bp 0
#define SAMPLERZ_AXI__CONSUMED_BITS__LOW_bw 32
#define SAMPLERZ_AXI__CONSUMED_BITS__LOW_reset 0x0
#define SAMPLERZ_AXI__CONSUMED_BITS__HIGH_bm 0xffffffff00000000
#define SAMPLERZ_AXI__CONSUMED_BITS__HIGH_bp 32
#define SAMPLERZ_AXI__CONSUMED_BITS__HIGH_bw 32
#define SAMPLERZ_AXI__CONSUMED_BITS__HIGH_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} samplerz_axi__consumed_bits_t;

// Reg - samplerz_axi::sw2hw64
#define SAMPLERZ_AXI__SW2HW64__LOW_bm 0xffffffff
#define SAMPLERZ_AXI__SW2HW64__LOW_bp 0
#define SAMPLERZ_AXI__SW2HW64__LOW_bw 32
#define SAMPLERZ_AXI__SW2HW64__HIGH_bm 0xffffffff00000000
#define SAMPLERZ_AXI__SW2HW64__HIGH_bp 32
#define SAMPLERZ_AXI__SW2HW64__HIGH_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} samplerz_axi__sw2hw64_t;

// Reg - samplerz_axi::hw2sw32
#define SAMPLERZ_AXI__HW2SW32__DATA_bm 0xffffffff
#define SAMPLERZ_AXI__HW2SW32__DATA_bp 0
#define SAMPLERZ_AXI__HW2SW32__DATA_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t data :32;
    } f;
    uint32_t w;
} samplerz_axi__hw2sw32_t;

// Reg - samplerz_axi::sw2hw32
#define SAMPLERZ_AXI__SW2HW32__DATA_bm 0xffffffff
#define SAMPLERZ_AXI__SW2HW32__DATA_bp 0
#define SAMPLERZ_AXI__SW2HW32__DATA_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t data :32;
    } f;
    uint32_t w;
} samplerz_axi__sw2hw32_t;

// Reg - samplerz_axi::prng::counter
#define SAMPLERZ_AXI__PRNG__COUNTER__LOW_bm 0xffffffff
#define SAMPLERZ_AXI__PRNG__COUNTER__LOW_bp 0
#define SAMPLERZ_AXI__PRNG__COUNTER__LOW_bw 32
#define SAMPLERZ_AXI__PRNG__COUNTER__HIGH_bm 0xffffffff00000000
#define SAMPLERZ_AXI__PRNG__COUNTER__HIGH_bp 32
#define SAMPLERZ_AXI__PRNG__COUNTER__HIGH_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} samplerz_axi__prng__counter_t;

// Regfile - samplerz_axi::prng
typedef struct __attribute__ ((__packed__)) {
    samplerz_axi__sw2hw32_t seed[11];
    uint8_t RESERVED_2c_2f[0x4];
    samplerz_axi__prng__counter_t counter;
} samplerz_axi__prng_t;

// Reg - samplerz_axi::hw2sw64
#define SAMPLERZ_AXI__HW2SW64__LOW_bm 0xffffffff
#define SAMPLERZ_AXI__HW2SW64__LOW_bp 0
#define SAMPLERZ_AXI__HW2SW64__LOW_bw 32
#define SAMPLERZ_AXI__HW2SW64__HIGH_bm 0xffffffff00000000
#define SAMPLERZ_AXI__HW2SW64__HIGH_bp 32
#define SAMPLERZ_AXI__HW2SW64__HIGH_bw 32
typedef union {
    struct __attribute__ ((__packed__)) {
        uint64_t low :32;
        uint64_t high :32;
    } f;
    uint64_t w;
} samplerz_axi__hw2sw64_t;

// Regfile - samplerz_axi::sample_histogram
typedef struct __attribute__ ((__packed__)) {
    samplerz_axi__hw2sw64_t histogram[40];
    samplerz_axi__hw2sw32_t pivot_value;
    samplerz_axi__hw2sw32_t pivot_index;
} samplerz_axi__sample_histogram_t;

// Addrmap - samplerz_axi
typedef struct __attribute__ ((__packed__)) {
    samplerz_axi__marker_t marker;
    samplerz_axi__control_t control;
    samplerz_axi__busy_cycles_t busy_cycles;
    samplerz_axi__consumed_bits_t consumed_bits;
    samplerz_axi__sw2hw64_t sginv;
    samplerz_axi__sw2hw64_t mu1;
    samplerz_axi__sw2hw64_t mu2;
    samplerz_axi__hw2sw32_t z1;
    samplerz_axi__hw2sw32_t z2;
    uint8_t RESERVED_38_3f[0x8];
    samplerz_axi__prng_t prng;
    uint8_t RESERVED_78_1ff[0x188];
    samplerz_axi__sample_histogram_t sample_histograms[2];
} samplerz_axi_t;


static_assert(sizeof(samplerz_axi_t) == 0x490, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* SAMPLERZ_AXI_BITFIELD_LITTLE_H */
